### ISSUE TITLE
Unable to resolve module StyleSheetRegistry

### ISSUE THREAD

**Issue by PhilippKrone** [jeanregisser/react-native-slider#1]
Hi,

I get the warning:
````javascript
Unable to resolve module StyleSheetRegistry
````

Everything seems to work correctly, just the message in the packager window.

**Comment by jeanregisser** [comment]
Thanks, I'll push a fix first thing tomorrow!

**Comment by jeanregisser** [comment]
Alright, fixed version 0.1.1 has been published on npm.
Again, thanks for reporting!
