### ISSUE TITLE
Jumps to start of slider

### ISSUE THREAD

**Issue by lewisbarber** [jeanregisser/react-native-slider#11]
When I try to slide the button it jumps to the start of the slider and only moves back to the position I slid it to when I release the mouse (in Simulator, iOS 9.1). I'm using version 0.4.0 of this element. Have you seen this issue before?

**Comment by lewisbarber** [comment]
I think it's because this: 

onValueChange={(amount) => this.setState({amount: amount})} 

Causes React to re-render the UI

**Comment by lewisbarber** [comment]
This works:

                            <Slider 
                                value={this.state.amount}
                                minimumValue={5}
                                maximumValue={100}
                                onValueChange={(amount) => this.setState({amount: amount})} 
                                onSlidingComplete={(amount) => this.setState({amount: amount})} 
                                thumbStyle={Styles.sheet.sliderThumb}
                                minimumTrackTintColor={Styles.colors.offBlackLightest}
                                maximumTrackTintColor={Styles.colors.offBlackLightest} />

This could be fixed by making the value parameter mandatory if onValueChange or onSlidingComplete are provided with a function (especially if that function calls setState)

**Comment by gauriladdad** [comment]
+1 on this issue

**Comment by jeanregisser** [comment]
Thanks for reporting this @lewisbarber, I've just published 0.6.0 on NPM with a fix to this.
