### ISSUE TITLE
Use Animated instead of setState

### ISSUE THREAD

**Issue by brentvatne** [jeanregisser/react-native-slider#14]
Right now using `setState` is fairly inefficient as you need to reconcile the entire component again on each frame of the touch -- if you were to use Animated the performance would much much smoother. Noticed this on a Nexus 5.

**Comment by rclai** [comment]
Yes, this is very not smooth and is causing a ton of CPU usage, however, this is a very nice plugin though.

**Comment by jeanregisser** [comment]
Thanks for reporting @brentvatne!
I'll switch to Animated as soon as I find some free time ;)

**Comment by brentvatne** [comment]
Agreed @rclai :)

Cool @jeanregisser! Looking forward to trying it

**Comment by jamesfzhang** [comment]
@jeanregisser Any plans on working on this within the next week?

**Comment by rclai** [comment]
I may do a PR now that I understand how `Animated` works.

**Comment by jamesfzhang** [comment]
@rclai That would be fantastic & much appreciated!

**Comment by jamesfzhang** [comment]
@rclai Have you started working on this?

**Comment by jeanregisser** [comment]
@jamesfzhang I haven't found the time yet ;)
@rclai would be awesome if you beat me to it :fireworks:

**Comment by jamesfzhang** [comment]
I took a stab at this. https://github.com/jeanregisser/react-native-slider/pull/17

**Comment by rclai** [comment]
Nice.

I did work on this and the part that @jamesfzhang took care of works nicely but I was having trouble getting the performance to be better when updating the Animated value on `_handlePanResponderMove`, or in other words, when I'm holding and panning. It performs a lot better, but is still not acceptable.

I'll PR my end when I get a chance for some reinforcements on that area.

**Comment by DVassilev** [comment]
@jeanregisser have you had a chance to look at the PR made above? If it is fine could you update the plugin on NPM please.

**Comment by williambout** [comment]
:+1: for using Animated

**Comment by talarari** [comment]
I tried the code from the pull request and it feels a lot better, any chance you could merge it and release a new version to npm?

**Comment by jeanregisser** [comment]
Thanks all!
I've finally published 0.6.0 on NPM which fixes performance issues while using the slider.
There's no more re-render while using it 🎉 

Let me know how it works for you.
