### ISSUE TITLE
Slider only works on 'debug in chrome mode'

### ISSUE THREAD

**Issue by yusufseyrek** [jeanregisser/react-native-slider#15]
Hello,
When i try to run, app is crashing. I think its about JSON Serialization err. Does anyone can help with that ?

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (NaN) in JSON write'

I'm using react-native 0.14.2
Thanks

**Comment by jeanregisser** [comment]
Fixed by fc53b4be6e9d495f880d60b34c406aae5037672a
Update is available on NPM.
