### ISSUE TITLE
Slider has minimumTrackTintColor sticking out on left side

### ISSUE THREAD

**Issue by JosephMulder** [jeanregisser/react-native-slider#154]
I get this ui problem where I can see the minimumTrackTintColor sticking out on left side when the value is 0. My slider is going to be default at 0 so to have it doing this looks really bad. 
    "react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-slider": "^0.11.0"

Made a clean repository with most basic code and I get the problem in the picture. Not sure if there is something that can fix this problem. 

      <View style={{flex: 1}}>
            <View style={{padding: 30, backgroundColor: '#cccccc'}}>
                    <Slider
                      style={{width: '100%'}}
                      value={this.state.value}
                      onValueChange={value => this.setState({ value })}
                      minimumValue={0}
                      maximumValue={10}
                      thumbStyle={{width: 60, height: 60, borderRadius: 30}}
                      trackStyle={{width: '100%', height: 60, borderRadius: 30, backgroundColor: '#BA2745'}}
                      minimumTrackTintColor='green'
                      onSlidingComplete={ val => console.log('hi')}
                    />
            </View>
      </View>

![screenshot_1549896305](https://user-images.githubusercontent.com/38866422/52570656-e1c22780-2de1-11e9-8d84-cfbc567bbca6.png)

**Comment by Fredsters** [comment]
Maybe do `minimumTrackTintColor='transparent'`
