### ISSUE TITLE
change orientation of slider.

### ISSUE THREAD

**Issue by christopher-18** [jeanregisser/react-native-slider#156]
I want to implement a slider vertically so that my slider works up to down, with up as the min value and down as max value.
I tried doing following
```
<Slider
                    **orientation={'vertical'}**
                    **inverted**
                    value={this.state.value}
                    onValueChange={value => console.log(value)}
                    thumbStyle={{
                    backgroundColor: 'white',
                    borderColor: "purple",
                    borderWidth: 3
                    }}
                    minimumTrackTintColor="purple"
                    // maximumTrackTintColor={}
                    step={1000}
                    minimumValue={1000}
                    maximumValue={10000}
                    />
```
Doing so, my slider is still working in horizontal direction with (left to right movement).
When i add following **inside the slider's style** as:
                  `  style={{ width: 200, marginHorizontal: 15,transform:[{rotate:'90deg'}],zIndex:3000,marginTop:30 }}`
my slider gets positioned vertically, but I am unable to move it further, it gets stuck at 2000 (on doing console) and then moves upwards automatically.

**Comment by uguraktas** [comment]
does the same problem, not work vertical ?
