### ISSUE TITLE
New release for npm

### ISSUE THREAD

**Issue by FlorianeEnnaji** [jeanregisser/react-native-slider#20]
Hi,
I saw previous commits removed peerDependencies but I still have the issue when I try to install your package through npm (`npm i --save react-native-slider`).
Could you please update npm ? I think you just have to make a new release.

**Comment by danielweinmann** [comment]
+1

**Comment by williambout** [comment]
:+1:

**Comment by jeanregisser** [comment]
Indeed, sorry for the delay.
Latest code with the removed peerDependencies is now available on NPM.
