### ISSUE TITLE
Slider only works in regular view.  If its a nested navigation view it doesnt

### ISSUE THREAD

**Issue by holoverse** [jeanregisser/react-native-slider#21]
I have a project thats using react-native-tabbar for navigation.
If I render the Slider in any one of the subviews.  It works just fine.

The problem arises when I "pop" out of the tabbar navigator into either a modal window, or another page outside of the tabbar navigator context.

If I try to render a Slider on any of these pages, it doesnt seem to work.

It appears its the _measureContainer method that is making it dissapear.  
Because if I remove that from the View tag, it displays, but its static and doesnt allow interaction.

Any idea why this is?

**Comment by jeanregisser** [comment]
I don't know yet. Do you have a small sample code to share for me to reproduce this?

**Comment by jeanregisser** [comment]
@holoverse I've just released 0.5.2 on NPM, let me know if it fixes your issue.
