### ISSUE TITLE
Perhaps should not receive value update via props

### ISSUE THREAD

**Issue by rreusser** [jeanregisser/react-native-slider#23]
Thanks for the component! It's soooo close to exactly what I need.

One small thing: The docs for [SliderIOS](https://facebook.github.io/react-native/docs/sliderios.html#value) state:

> Initial value of the slider. …
> *This is not a controlled component, e.g. if you don't update the value, the component won't be reset to its initial value.*

However, this component receives prop updates that affect the value. Should that simply be removed so that the component gets an initial value but not further updates?

**Comment by jeanregisser** [comment]
Hi @rreusser,

As discussed in https://github.com/jeanregisser/react-native-slider/pull/24#issuecomment-205746032
the current implementation matches what `SliderIOS` does.
When you update the value prop it changes the thumb position. But you don't have to change the value prop after interacting with the thumb for it to stay at its position where you lifted your finger.

Let me know if all is clear.

**Comment by rreusser** [comment]
Good catch! My mistake. I misinterpreted the what "not controlled meant." My code was accidentally modifying the value which in turn prevented the slider from being movable. Thanks for the clarification!
