### ISSUE TITLE
Merge + publish small fixes/tweaks

### ISSUE THREAD

**Issue by rreusser** [jeanregisser/react-native-slider#26]
Thanks so much for this module! I'm not aware of a different native drop-in for android yet, so I did my best to clean up a couple small issues, pull things together, and document the changes. You can see the result at: https://github.com/rreusser/react-native-slider

I know how much work it is to maintain open source stuff like this, but I really appreciate you putting this together and would be glad to merge and publish #9, #10, #24, and #25 (I had trouble getting #17 working :disappointed:) if you think those changes are the right move and if given permission.

Otherwise anyone is welcome to use my fork if these tweaks seem like the right move. :+1:

Thanks!

**Comment by jeanregisser** [comment]
Hi @rreusser, nice work on these!
I'm looking at merging them right now.

#9 merged!
#10 I'm not entirely convinced we should add this feature with a callback. `onValueChange` is already being called continuously, maybe we could pass the thumb position as a 2nd argument? Or add a public method returning the position which developers could call from `onValueChange` ? Any thoughts?
#17 is incomplete and is gonna need a bit more work indeed.
#24 merged!
#25 merged!

Thanks again for taking the time to clean up those issues. I've been rather busy in the past months.
I'm pushing a new update today to NPM with the merged fixes / additions.

**Comment by jeanregisser** [comment]
Updated is available on NPM!
