### ISSUE TITLE
Events don't fire with onPanResponderTerminationRequest: () => false

### ISSUE THREAD

**Issue by alexHlebnikov** [jeanregisser/react-native-slider#30]
Hi.

I have the problem: slider stops work if I add these lines
```
 componentWillMount() {
        this._panResponder = PanResponder.create({
            onPanResponderTerminationRequest: () => false,
            onStartShouldSetPanResponderCapture: () => true,
        });
```
If I correctly understand it's because PanResponder is used inside slider and code above will prevent events form bubbling. 
But I need this code for my parent component (it's a panel with some other components inside and you can drag it up or down) because I don't want to make drag event work on slider component.

Here is my code:
```
class Filter extends Component {
    state = {
        value: 1,
    }

    componentWillMount() {
        this._panResponder = PanResponder.create({
            // prevent drag event from parent component
            onPanResponderTerminationRequest: () => false,
            onStartShouldSetPanResponderCapture: () => true,
        });
    }

    render() {
        return (
            <View style={styles.filterWrap} {...this._panResponder.panHandlers} >
                <Slider
                    step={1}
                    trackStyle={styles.track}
                    thumbStyle={styles.thumb}
                    minimumValue={0}
                    maximumValue={2}
                    minimumTrackTintColor='rgba(0,0,0,0)'
                    maximumTrackTintColor='rgba(0,0,0,0)'
                    thumbTintColor='#fff'
                    style={styles.slider}
                    value={this.state.value}
                    onValueChange={(value) => this.setState({value})} />
            </View>
        );
    }
}
```

Is there any way to prevent events from my parent component on Slider component and enable events in slider PanResponder?

**Comment by jeanregisser** [comment]
Hi @alexHlebnikov, what version of react-native-slider are you using?

**Comment by alexHlebnikov** [comment]
@jeanregisser I'm using latest version.

**Comment by alexHlebnikov** [comment]
My description might be a little be confusing. 
Just, in two words: I have component named **Panel**, it's a wrapper for components **Info** and **Filter** (here is the Slider). 
I'm added animations to **Panel** so I can drag it in Y direction on swipe (up and down), I'm doing it with **PanResponder**. But I don't want the drag event to be fired when I tap on **Filter** component (because it's not comfortable for using). So i use `onPanResponderTerminationRequest: () => false` and `onStartShouldSetPanResponderCapture: () => true`, in my **Filter** and it works great for dragging. But, tap or drag on slider stops working.

**Comment by jeanregisser** [comment]
Ok, I don't know how long you've been using react-native-slider, but since e41a935 (so 0.5.2) the slider is preventing other components from stealing touch events while interacting with it.

Unless I'm misunderstanding your use case, you should get the behavior you want by removing the pan handlers you added to your `Filter` component.
Or is that component bigger and you also don't want any drag anywhere in that component?

**Comment by alexHlebnikov** [comment]
I'll check older version, thanks!
If I remove pan handlers from `Filter` the whole panel will be slightly dragging up and down while I trying just to move slider thumb, but I don't want this behavior.

**Comment by alexHlebnikov** [comment]
So, I've found the mistake in my code, slider works brilliant now, @jeanregisser thank you for help!

**Comment by jeanregisser** [comment]
Nice! Glad you figured it out :+1:
