### ISSUE TITLE
Can we bump dependency to react 15?

### ISSUE THREAD

**Issue by jeveloper** [jeanregisser/react-native-slider#37]
just a small change to package.json ,  assuming 0.7.x is for RN 0.26+

**Comment by jeanregisser** [comment]
You mean for the react-addons-shallow-compare dependency?

**Comment by jeveloper** [comment]
Correct

**Comment by jeanregisser** [comment]
I've published 0.8.0 on npm with the change.
Thanks for reporting @jeveloper!
