### ISSUE TITLE
Constant rerenders on Android

### ISSUE THREAD

**Issue by cornedor** [jeanregisser/react-native-slider#50]
The Slider keeps rerendering on Android, resulting in bad performance when adding more Sliders.

Using 1 Slider: https://a.pomf.cat/nqxmdv.mp4
An extreme example: https://a.pomf.cat/jowuvd.mp4

**Comment by jeanregisser** [comment]
Ok interesting. 
I took care of preventing this, so there must be something failing.

Which version are you using? with which React Native version?

**Comment by cornedor** [comment]
I've created a brand new project to test this but I found the issue using react native 0.28.0. But the app recorded in the video is using react native 0.31.0. They are both using react-native-slider  0.9.0.

**Comment by jeanregisser** [comment]
Does it happen on a real device?
I've seen a case where the `onLayout` event, which the slider relies on for positioning the thumb, is called constantly with slightly different measures. But I was able to reproduce that only with Genymotion.

**Comment by cornedor** [comment]
The recordings are from my device (Nexus 5X). I did see the thumbs jump a bit, so it might be the same issue.

**Comment by jeanregisser** [comment]
What's the tool you're using which shows the graph and flashes re-render?

**Comment by cornedor** [comment]
In the Android Developer options "Show GPU view updates" and "Profile GPU rendering" set to "On screen as bars"

**Comment by jeanregisser** [comment]
Ok thanks, I tested it on a Nexus 5 and couldn't reproduce.
I think it's very likely to be the `onLayout` issue I was talking about which happens reliably on a Nexus 5X.
Do you happen to have a Nexus 5 to confirm this?

**Comment by jeanregisser** [comment]
Alright, I can reliably reproduce the problem with a 5X emulator.

**Comment by jeanregisser** [comment]
@cornedor I've justed published 0.9.1 on npm with a fix for this. 🎉 
Let me know how it works for you.

**Comment by cornedor** [comment]
@jeanregisser thanks!
https://a.pomf.cat/ghgxdm.mp4
