### ISSUE TITLE
It is possible to touch track and set value?

### ISSUE THREAD

**Issue by Micjoyce** [jeanregisser/react-native-slider#56]

**Comment by gyzerok** [comment]
Yeah, I am interested as well since it seem to be expected behaviour on Andorid

**Comment by asgvard** [comment]
Would be nice to have, I'm using this package for video progress slider, and didn't found a good way on setting value just by touching the track, w/o actual sliding.

**Comment by asgvard** [comment]
And seems like duplicate of #45 ?

**Comment by CaffGeek** [comment]
Same.

**Comment by LEEY19** [comment]
anyone has any progress on this? I am looking to set value by touching track as well
