### ISSUE TITLE
Thumb is above the track?

### ISSUE THREAD

**Issue by vincentaudebert** [jeanregisser/react-native-slider#63]
Am I the only one having this kind of issue?

![screen shot 2017-03-08 at 6 30 51 pm](https://cloud.githubusercontent.com/assets/3360430/23691492/a14c0a2a-042d-11e7-99ad-e144765893aa.png)

Also note that the back track is gone.

Here is my code: (Footer comes from native-base)

```
<Footer style={{
    backgroundColor: '#7DC265',
}}>
            <Slider
                style={{ flex: 1, alignSelf: 'stretch', margin: 10, alignItems: 'baseline' }}
                minimumValue={0} maximumValue={100}
                value={volume}
                trackStyle={{
                    height: 4,
                    borderRadius: 2,
                }}
                thumbStyle={{
                    width: 15,
                    height: 15,
                    backgroundColor: 'white',
                    borderColor: '#30a935',
                    borderWidth: 2
                }}
                minimumTrackTintColor='#30a935'
                onValueChange={value => debounce(volumeChange(value), 150)}
            />
</Footer>
```

I'm using:
```
    "native-base": "^2.0.12",
    "react-native": "0.42.0",
    "react-native-elements": "^0.9.7",
    "react-native-vector-icons": "^4.0.0",
```

**Comment by asgvard** [comment]
Hi,

I'm having the same issue from RN 0.42, what I did is I added "top: 29" to thumb style. Which is ugly of course...I was trying to debug it, it seems like it has something to do with the logic that applies to transformation:
https://github.com/jeanregisser/react-native-slider/blob/master/src/Slider.js#L276

But not sure yet, didn't had time to find a proper way of fixing it, just using the workaround with "top" offset.

**Comment by gyzerok** [comment]
Same issue here.

**Comment by vincentaudebert** [comment]
Thanks for the temp fix @asgvard that will do it for now :)

**Comment by mcnamee** [comment]
Thanks @asgvard - I did a `thumbStyle={{ top: 22 }}` which put it right in the centre for me

**Comment by creeperyang** [comment]
The same issue. I check the source code and found the position part is not quite correct. Do you need a pr?

**Comment by jeanregisser** [comment]
@creeperyang please do send a PR if you have a fix! 👍  Thanks

**Comment by creeperyang** [comment]
I send the pr <https://github.com/jeanregisser/react-native-slider/pull/65> just now. But I'm not quite sure it will solve all your problem.

**Comment by encorex** [comment]
same here...

**Comment by samridhgupta** [comment]
I was facing the same issue, but it was solved by making this change in **slider.js**

`transform: [
                { translateX: thumbLeft },
                { translateY: -(trackSize.height + thumbSize.height) / 2 }
              ],`
to 
 `transform: [
                { translateX: thumbLeft },
                { translateY: 0 }`

Would be  very helpful is someone push the solution asap.

**Comment by aurnik** [comment]
@samridhgupta I tried your solution with no success, what led you to that answer?

**Comment by amesf** [comment]
Thanks @mcnamee The magic number for me was top: 26. It's not consistent but you can find the right value by trial and error.

**Comment by samridhgupta** [comment]
@aurnik replying late ... you can check out my fork version of this component 
[https://github.com/samridhgupta/react-native-slider](url)

**Comment by RobinBobin** [comment]
Thanks a lot, that worked for me!

**Comment by efournival** [comment]
Hi, sorry for the noob question: how to import `samridhgupta/react-native-slider` instead of the default `react-native-slider`? 

I tried `npm uninstall react-native-slider` and `npm install https://github.com/samridhgupta/react-native-slider.git` but then, when I launch `react-native run-android`, a red screen pops telling me it has been unable to resolve the module with:
```javascript
import Slider from 'react-native-slider'
```

This: https://github.com/facebook/react-native/issues/4968 (I also tried all the workarounds, and `node_modules/react-native-slide` is there)

Is there something that I am missing?

Thank you

**Comment by RobinBobin** [comment]
Hi there!

You know, I failed to install samridhgupta/react-native-slider and I had no time to deal with that, so I just created a file named "Slider.js" in my src directory and imported from there. Ugly but stone-proof :) .

You're very welcome,

Robin.

**Comment by jeanregisser** [comment]
A fix for this has (finally) landed :tada: Use the latest published version (0.10.0)!
Thanks everyone.

**Comment by efournival** [comment]
Thank you so much both of you!

**Comment by jinxac** [comment]
Hey this wont work form react native version 0.40 right?

**Comment by efournival** [comment]
As I don't know if you wanted to write "for" or "from": I can confirm this is working with RN 0.45.1.
