### ISSUE TITLE
Support React Native 0.43+ / React 16+

### ISSUE THREAD

**Issue by brunolemos** [jeanregisser/react-native-slider#66]
EDIT: Submitted a PR fix: https://github.com/jeanregisser/react-native-slider/pull/67 

--

Somethings were removed / moved on React 16 and broke this lib.
Check [this article](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) from React.

E.g. "Unable to resolve module `react/lib/shallowCompare` ([article](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#discontinuing-support-for-react-addons)):

<img src="https://cloud.githubusercontent.com/assets/619186/24883913/7318326e-1e1d-11e7-998b-b99ca6557a41.png" height="400" />

**Comment by zhuyifan2013** [comment]
how about the progress?

**Comment by jeanregisser** [comment]
I've just merge and published this!
Again thanks a lot @brunolemos! 🎉
