### ISSUE TITLE
Is there a way to lock the slider?

### ISSUE THREAD

**Issue by manask88** [jeanregisser/react-native-slider#7]
I have a use case where I want to show the slider, but i dont want the user to be able to move the slider. Is there any way that I can implement my use case with the current compoment as it is?. If not, is there any plan to support this feature?

**Comment by jeanregisser** [comment]
Hi @manask88

You should be able to prevent any interaction by adding `pointer-events: none;` to the slider style.

Let me know if it works

**Comment by realjamie** [comment]
Hi @jeanregisser , do you mean styling the slider like this? 
<Slider style={{pointerEvents: 'none'}} />
It doesn't disable the slider.

**Comment by realjamie** [comment]
I also tried trackStyle and thumbStyle but they doesn't work.

**Comment by manask88** [comment]
@jeanregisser , I tried what you suggested but didnt work. So, I went ahead and implemented a new property that would allow to disable the slider. Please, take a look at my PR https://github.com/jeanregisser/react-native-slider/pull/9

**Comment by jeanregisser** [comment]
Thanks for your contribution @manask88! :+1: 
A new release is available on NPM with it,
