### ISSUE TITLE
Compatibility issues.

### ISSUE THREAD

**Issue by OrangeTangoButterfly** [jeanregisser/react-native-slider#74]
# Hello author,

  ## At the beginning,

  RN-version = **0.41.2** and react-version = **15.4.2**, the slider on version **0.9.1** works well;

  RN-version = **0.46.0** and react-version = **16.0.0-alpha.12**, the slider on version **0.9.1** works bad, like this:
       
![image](https://user-images.githubusercontent.com/13601583/28310109-ef2d0736-6bdd-11e7-9e06-06992ca24af4.png)

##   Then, 
  RN-version = **0.46.0** and react-version = **16.0.0-alpha.12**, the slider on version **0.10.0** doesn't work,
  with the error message:
  
_Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object._

  ## Last, my slider code here:

```
         <Slider
          style={{ width: width - 60, marginTop: 10, justifyContent:'center', height:50}}
          value={func.curtain_percent / 100}
          onSlidingComplete={(value) => this._onSlidingComplete(value)}
          thumbTouchSize={{width:60, height:60}}
          thumbStyle={{justifyContent:'center', alignItems:'center'}}
          trackStyle={{backgroundColor:'#eeeeee'}}
          thumbTintColor="#4790ff"
          minimumTrackTintColor='#4790ff'
          maximumTrackTintColor='#494949'
          onValueChanged={()=>{}}/>
```

   ## Last, can you help me on this issue? Thanks.

**Comment by eladgel** [comment]
just write this
`import Slider from 'react-native-slider';
`
