### ISSUE TITLE
[Tip] Way to implement snap functionality

### ISSUE THREAD

**Issue by bang9** [jeanregisser/react-native-slider#90]
#68 Snap functionality can be implement like this

```jsx
onChange = (value) => {
    let val = Math.round(value);
    if(this.state.value == val)
        this.slider._setCurrentValueAnimated(val);
    else
        this.setState({value:val});
}

<Slider
    value={this.state.value}
    ref={ref => this.slider = ref}
    onSlidingComplete={this.onChange}
    ...
/>
```
![image](https://user-images.githubusercontent.com/26326015/32559285-26acb5e8-c4ea-11e7-807e-c078f4a3ea95.gif)
It works very well for me, test it on [expo snack](https://snack.expo.io/@bang9/snap-slider)

**Comment by bharatidudhrejiya** [comment]
Can I change position of value displayed with position of slider
