### ISSUE TITLE
View Custom Styles?

### ISSUE THREAD

**Issue by maryammouse** [jeanregisser/react-native-slider#96]
In the readme for this project, there are several custom styles displayed -- I was under the impression that I would be able to use these for the slider when I installed this, but I don't see how? Alternatively, I would love to see the code for them simply to help me style my own sliders -- as a newbie, I have no idea what the syntax is. Actually, having some documentation in the README about how exactly the styling for the thumb and the track work, would be great. (i.e. in my specific case, I just want to be able to make the track thinner than the default slider has it, but I have no idea how or what attribute I need to change)

**Comment by yashojha19** [comment]
Each of the custom style is implemented here.
https://github.com/jeanregisser/react-native-slider/blob/master/Example/app.js 
have to set some props such as. minimumTrackTintColor, maximumTrackTintColor, thumbTintColor and can give styles as thumbStyle,trackStyle :)

**Comment by maryammouse** [comment]
Oh, totally missed that file! Really appreciate this, thanks! :)
